export const IMAGE_TAG_LIST = [
    "support-card",
    "story-event",
    "game-art",
    "twitter-art",
    "twitter-g1",
    "key-visual",
    "character-art",
    "merch",
    "anime",
    "umayon",
    "umayuru",
    "album-cover",
    "manga-cover",
    "cinderella-gray",
    "star-blossom",
    "umamusumeshi",
    "starting-gate-manga",
    "collaboration",
    "live-event",
    "magazine",
    "instagram",
] as const;

export type ImageTag = (typeof IMAGE_TAG_LIST)[number];
export const IMAGE_TAG_NAMES: { [k in ImageTag]: string } = {
    "album-cover": "Album Covers",
    "character-art": "Character Art",
    "cinderella-gray": "Cinderella Gray",
    "game-art": "Game Art",
    "key-visual": "Key Visuals",
    "live-event": "Live Event Visuals",
    "manga-cover": "Manga Covers",
    "starting-gate-manga": "Starting Gate Manga",
    "story-event": "Story Event Stills",
    "support-card": "Support Cards",
    "twitter-art": "Official Twitter Art",
    "twitter-g1": "Twitter G1 Race Art",
    anime: "Anime Visuals",
    collaboration: "Collaborations",
    instagram: "Instagram Posts",
    magazine: "Magazines",
    merch: "Merchandise",
    umayon: "Umayon",
    umayuru: "Umayuru",
    "star-blossom": "Star Blossom",
    umamusumeshi: "Umamusumeshi",
};
