name: Build

on:
  push:
    branches: master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci --omit=dev
      - run: npm run build
        env:
          DIRECTUS_ENDPOINT: https://admin.uma.cafe
          DIRECTUS_TOKEN: ${{ secrets.DIRECTUS_TOKEN }}
      - uses: andreiio/rclone-action@v1
        with:
          args: sync dist r2:uma-cafe-main
        env:
          RCLONE_CONFIG_R2_TYPE: s3
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
